version: '3'

services:
  ##> doctrine/doctrine-bundle ###
  database:
    image: mariadb:11.2.2
    environment:
      MARIADB_ROOT_PASSWORD: password
    restart: on-failure
    ports:
      - "3307:3306"
    volumes:
      - amazon_db:/var/lib/mysql

volumes:
  amazon_db:
    driver: local